// SPDX-License-Identifier: MIT
//
// The index record must be byte-identical to what the Python client writes, because a
// recording made here is read there. This is the one place the two languages have a hard
// contract, so it is pinned against bytes that Python actually produced rather than
// against a restatement of the spec.
//
// The vectors below came from:
//
//   PYTHONPATH=vcap_py python3 -c \
//       "from vcap.index import pack; print(pack(1, 2, 3, 4, 5, 6).hex())"
//
// If this test fails, the two clients disagree about the file format and every recording
// written by one and read by the other is wrong -- silently, because a misread index
// yields plausible offsets into a real file.
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "vcap/index.hpp"

namespace {

int failures = 0;

struct Case {
    std::uint64_t offset;
    std::uint32_t length;
    std::int64_t ts;
    std::uint32_t seq, flags, dropped;
    std::uint8_t expected[vcap::kIndexRecordSize];
};

// Generated by vcap/index.py. Do not hand-edit: regenerate if the format version changes.
const Case kCases[] = {
    {0, 0, 0, 0, 0, 0,
     {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00}},
    {1, 2, 3, 4, 5, 6,
     {0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x03, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
      0x06, 0x00, 0x00, 0x00}},
    // A real record from a 4-minute capture: the frame either side of a segment boundary,
    // with a gap flag set.
    {2146625835u, 302727u, 340905782457000LL, 6892u, 2u, 1u,
     {0x2b, 0xe9, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x87, 0x9e, 0x04, 0x00, 0xa8, 0xb2,
      0x10, 0x50, 0x0d, 0x36, 0x01, 0x00, 0xec, 0x1a, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
      0x01, 0x00, 0x00, 0x00}},
    // Field boundaries: every field saturated, to catch a width or an offset that is
    // wrong only for large values.
    {0xFFFFFFFFFFFFFFFFull, 0xFFFFFFFFu, 0x7FFFFFFFFFFFFFFFLL, 0xFFFFFFFFu, 7u, 0xFFFFFFFFu,
     {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
      0xff, 0xff, 0xff, 0xff, 0xff, 0x7f, 0xff, 0xff, 0xff, 0xff, 0x07, 0x00, 0x00, 0x00,
      0xff, 0xff, 0xff, 0xff}},
};

void check_case(const Case& c, int n) {
    std::uint8_t got[vcap::kIndexRecordSize];
    vcap::pack_index_record(got, c.offset, c.length, c.ts, c.seq, c.flags, c.dropped);
    if (std::memcmp(got, c.expected, sizeof got) != 0) {
        ++failures;
        std::printf("  FAIL  case %d encodes differently from Python\n", n);
        std::printf("        want ");
        for (std::size_t i = 0; i < sizeof got; ++i) std::printf("%02x", c.expected[i]);
        std::printf("\n        got  ");
        for (std::size_t i = 0; i < sizeof got; ++i) std::printf("%02x", got[i]);
        std::printf("\n");
    }
}

}  // namespace

int main() {
    if (vcap::kIndexRecordSize != 32) {
        ++failures;
        std::printf("  FAIL  record is %zu bytes, the format says 32\n",
                    vcap::kIndexRecordSize);
    }
    int n = 0;
    for (const auto& c : kCases) check_case(c, n++);

    // Frame N lives at byte 32N; that arithmetic is what makes random access O(1), so it
    // is worth stating rather than leaving implicit in the reader.
    if (vcap::kIndexRecordSize * 1000 != 32000) {
        ++failures;
        std::printf("  FAIL  record stride does not scale as expected\n");
    }

    if (failures == 0) {
        std::printf("  ok    index records encode identically to the Python client\n");
    }
    return failures ? 1 : 0;
}
